version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: laihuuloi
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data # Để lưu trữ dữ liệu Redis bền vững

volumes:
  redisdata:
    driver: local